### ISSUE TITLE
脚本运行错误

### ISSUE THREAD

**Issue by Tobyyyzz** [CrazyHer/Deploy-codeserver-on-termux#1]
你好！我尝试在termux上运行你的一键脚本，显示出错

**Comment by CrazyHer** [comment]
抱歉，由于[atilo](https://github.com/YadominJinta/atilo)已经停止维护很长一段时间了，目前已经无法依靠其安装ubuntu并通过proot启动。
请试试[tmoe](https://github.com/2moe/tmoe-linux)在termux上部署ubuntu并安装code-server，
或直接在termux中`npm install -g code-server`进行安装并启动
